### ISSUE TITLE
Increase redirection count

### ISSUE THREAD

**Issue by arjungarg07** [arjungarg07/urlshortener#11]
Currently the `redirectCount` path defined in the `Url` schema is not being updated after every successful redirect of the Url which needs to increased by 1 after successful redirect.

**Comment by Harshith2255** [comment]
Hi I would like to work on this issue

**Comment by arjungarg07** [comment]
Hey @Harshith2255, I would be happy to assign you, but @BalgopalPatro has already solved the issue. You can look up on other issues. Thanks!

**Comment by Creatoon** [comment]
is this still open ? can i work on this

**Comment by arjungarg07** [comment]
Hey @Creatoon, this issue is resolved. However, you can look at other opened issues.
