### ISSUE TITLE
Copy button functionality

### ISSUE THREAD

**Issue by arjungarg07** [arjungarg07/urlshortener#14]
Copy button is not working correctly. Generated link should be copied to the clipboard after clicking the button.

**Comment by balaji2210** [comment]
> Copy button is not working correctly. Generated link should be copied to the clipboard after clicking the button.

It's done

**Comment by balaji2210** [comment]
this issue is resolved

**Comment by harshil15999** [comment]
@arjungarg07 please close this if done
