### ISSUE TITLE
login/sign-up and logout APIs

### ISSUE THREAD

**Issue by arjungarg07** [arjungarg07/urlshortener#20]
We are introducing a login/sign-up functionality for users using passport and jwt-authentication. This feature will introduce many other possibilities we can provide to respective users. Follow the REST architectural style for implementing these APIs.

**Comment by ChandanaReddy07** [comment]
I want to work on this issue..

**Comment by shrirangpdeshmukh** [comment]
I want to work on this

**Comment by arjungarg07** [comment]
Go ahead @dcr7978933k

**Comment by arjungarg07** [comment]
Hey, @shrirangpdeshmukh, I am sorry to say but @dcr7978933k  and @majjikishore007 asked for it earlier. However, you can work on other issues.
For regular updates join our slack channel.

**Comment by majjikishore007** [comment]
i am working on it

**Comment by arjungarg07** [comment]
> I want to work on this

Hey @shrirangpdeshmukh, You can work on logging in a user by google auth. Open a new issue and start working on it

**Comment by rahulgogia65** [comment]
>You can work on logging in a user by google auth. 

Has this been done?
