### ISSUE TITLE
Providing QR codes 

### ISSUE THREAD

**Issue by arjungarg07** [arjungarg07/urlshortener#22]
Provide the QR code for the generated short-URLs so that the user can have the QR code image. QR codes promote **interaction** and **engagement** through the mobile phone. It can be used by businesses to redirect users to their products. This is useful as short-URLs are easy and faster to scan in comparison to long URLs.
**Refer**: API for generating [QR codes](http://goqr.me/api/)

**Comment by arnabsen1729** [comment]
@arjungarg07 I want to work on this issue. Please assign me.

**Comment by arjungarg07** [comment]
Sure,Go ahead @arnabsen1729
