### ISSUE TITLE
Login using Google Auth

### ISSUE THREAD

**Issue by shrirangpdeshmukh** [arjungarg07/urlshortener#24]
**Describe the feature**
The user can log in to the WebApp using Google API.
Planing to use PassportJs and Google Strategy 2. 

**Screenshots if any**

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by arjungarg07** [comment]
I have provided you the template. Please fill it accordingly. Thanks!

**Comment by shrirangpdeshmukh** [comment]
I have completed the implementation of Backend for Google Auth.
We can login through Google by going to /auth/google.
[The changes I made are here](https://github.com/shrirangpdeshmukh/Brief-Me/commit/2674b2cf2d2f6aac7664fdedd6edb6fb9c877ee8).
I don't know how we are going to implement it for the front end, can you elaborate on that

**Comment by arjungarg07** [comment]
What parameters did you consider which will be coming from the client-side?

**Comment by shrirangpdeshmukh** [comment]
I assumed we will be having a normal button for google signup, like this

![](https://miro.medium.com/max/1104/1*HHM0sJKRnksQxoEebvbZmQ.png)

onClick this backend authentication will be used

**Comment by arjungarg07** [comment]
Yeah, that's correct. Thanks!
